# Generated by Django 5.1.4 on 2026-01-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
