# Generated by Django 5.1.4 on 2026-01-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_is_active',
        ),
    ]
