# Generated by Django 5.1.4 on 2026-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
