# Generated by Django 5.1.4 on 2026-02-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0013_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_doctor', 'date_joined'], name='users_user_is_doct_f81a25_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_customer'], name='users_user_is_cust_ac5790_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
    ]
