# Generated by Django 5.1.4 on 2025-04-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='customer',
        ),
    ]
