# Generated by Django 5.1.4 on 2025-09-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_appointment_options_and_more'),
        ('doctor', '0013_remove_doctor_experience_remove_doctor_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_for',
            field=models.CharField(choices=[('Book For Your Self', 'Book For Your Self'), ('Booking For Someone Else', 'Booking For Someone Else')], default='Book For Your Self', max_length=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctor', to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
