# Generated by Django 5.1.4 on 2025-09-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_appointment_booking_for_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='waiting', max_length=20),
        ),
    ]
