# Generated by Django 5.1.4 on 2025-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_ticketmessage_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
