# Generated by Django 5.1.4 on 2025-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_ticketmessage_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='service',
            field=models.CharField(choices=[('aligners', 'Book Aligners'), ('skin', 'Book Skin/Hydrafacial')], default='aligners', max_length=50),
        ),
    ]
