# Generated by Django 5.1.4 on 2025-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_supportticket_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('aligners', 'Book Aligners'), ('skin', 'Book Skin/Hydrafacial')], default='aligners', max_length=50),
        ),
    ]
