# Generated by Django 5.1.4 on 2025-09-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_dob_remove_customer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
