# Generated by Django 5.1.4 on 2025-09-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_appointment_time_appointment_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booking_for',
        ),
    ]
