# Generated by Django 5.1.4 on 2025-09-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_appointment_booking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
