# Generated by Django 5.1.4 on 2025-12-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_subscriptionplan_subscription_subscriptionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='paiddoubt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
