# Generated by Django 5.1.4 on 2026-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('next_appointment', 'Next Appointment')], default='waiting', max_length=20),
        ),
    ]
