# Generated by Django 5.1.4 on 2026-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Confirmation'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rescheduled_by_patient', 'Rescheduled by Patient'), ('next_appointment', 'Next Appointment')], default='waiting', max_length=30),
        ),
    ]
