# Generated by Django 5.1.4 on 2026-01-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiddoubt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
    ]
