# Generated by Django 5.1.4 on 2026-02-07 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_notification'),
        ('doctor', '0056_doctor_weekly_off_days'),
        ('masters', '0034_coupon_masters_cou_is_acti_c16876_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', '-created_at'], name='customer_ap_user_id_308186_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date'], name='customer_ap_doctor__96db8d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date', 'status'], name='customer_ap_doctor__37e84f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-created_at'], name='customer_ap_created_46bc67_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='customer_no_user_id_c8f76f_idx'),
        ),
        migrations.AddIndex(
            model_name='paiddoubt',
            index=models.Index(fields=['payment_status', '-created_at'], name='customer_pa_payment_e13d44_idx'),
        ),
        migrations.AddIndex(
            model_name='paiddoubt',
            index=models.Index(fields=['user', 'payment_status'], name='customer_pa_user_id_4fdd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='customer_su_user_id_efc83e_idx'),
        ),
    ]
