# Generated by Django 5.1.4 on 2025-05-13 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_enquiry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='treatment',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='area',
            field=models.CharField(default='wewewe', max_length=150, verbose_name='Locality/Area/street/Sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dob',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 21, 27, 22, 394198, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(default='sdsd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='house',
            field=models.CharField(default='Sdsd', max_length=100, verbose_name='House/Building/Apartment No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
