# Generated by Django 5.1.4 on 2025-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_rename_address_enquiry_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('home _visit', 'Home Visit'), ('aligners', 'Aligners'), ('skin_hydrafacial', 'Skin/Hydrafacial')], default='Pending', max_length=20),
        ),
    ]
