# Generated by Django 5.1.4 on 2025-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('home_visit', 'Home Visit'), ('aligners', 'Aligners'), ('skin_hydrafacial', 'Skin/Hydrafacial')], default='Pending', max_length=20),
        ),
    ]
