# Generated by Django 5.1.4 on 2025-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_treatment_treatmentstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
