# Generated by Django 5.1.4 on 2025-09-12 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_treatment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentstep',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='masters.treatment'),
        ),
    ]
