# Generated by Django 5.1.4 on 2025-09-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_helpquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquestion',
            name='for_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
