# Generated by Django 5.1.4 on 2025-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_alter_enquiry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('aligners', 'Aligners'), ('skin_hydrafacial', 'Skin/Hydrafacial')], default='Pending', max_length=20),
        ),
    ]
