# Generated by Django 5.1.4 on 2025-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_alter_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
