# Generated by Django 5.1.4 on 2025-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_alter_enquiry_dob_alter_enquiry_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
