# Generated by Django 5.1.4 on 2025-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_alter_enquiry_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='booking_type',
            field=models.CharField(choices=[('self', 'Booking for Yourself'), ('other', 'Booking for Someone Else')], default='self', max_length=10),
        ),
    ]
