# Generated by Django 5.1.4 on 2025-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_enquiry_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Locality/Area/street/Sector'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='House/Building/Apartment No.'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
