# Generated by Django 5.1.4 on 2025-10-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_prescription_prescriptionmedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('aligners', 'Aligners'), ('skin_hydrafacial', 'Skin/Hydrafacial'), ('home_visit', 'Home Visit')], default='Pending', max_length=20),
        ),
    ]
