# Generated by Django 5.1.4 on 2025-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_alter_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
