# Generated by Django 5.1.4 on 2026-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_alter_prescriptionmedicine_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='power',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose_time',
            field=models.JSONField(default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']"),
        ),
        migrations.AddField(
            model_name='medicine',
            name='meal_relation',
            field=models.CharField(blank=True, choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal')], max_length=30, null=True),
        ),
    ]
