# Generated by Django 5.1.4 on 2026-01-10 11:57

from django.db import migrations, models
import json


def set_default_dose_time(apps, schema_editor):
    """Set default empty list for existing records with invalid/null dose_time"""
    Medicine = apps.get_model('masters', 'medicine')
    for medicine in Medicine.objects.all():
        # Ensure all records have valid JSON (empty list if None or invalid)
        try:
            if medicine.dose_time is None or not isinstance(medicine.dose_time, list):
                medicine.dose_time = []
                medicine.save(update_fields=['dose_time'])
        except (AttributeError, TypeError, ValueError):
            # If there's any error, set to empty list
            medicine.dose_time = []
            medicine.save(update_fields=['dose_time'])


def reverse_set_default_dose_time(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_remove_medicine_power_medicine_dose_time_and_more'),
    ]

    operations = [
        # First, ensure all existing records have valid JSON
        migrations.RunPython(set_default_dose_time, reverse_set_default_dose_time),
        # Then alter the field to allow null
        migrations.AlterField(
            model_name='medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
