# Generated by Django 5.1.4 on 2026-01-10 12:00

import masters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_alter_medicine_dose_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=masters.models.default_dose_time, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
