# Generated by Django 5.1.4 on 2026-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_alter_medicine_dose_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity in stock', max_digits=10, null=True),
        ),
    ]
