# Generated by Django 5.1.4 on 2026-01-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_medicine_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
    ]
