# Generated by Django 5.1.4 on 2026-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_remove_medicine_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True),
        ),
    ]
