# Generated by Django 5.1.4 on 2026-01-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_medicine_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_banner',
            name='description',
        ),
        migrations.AddField(
            model_name='home_banner',
            name='link',
            field=models.URLField(blank=True, help_text='URL link for the banner', null=True),
        ),
    ]
