# Generated by Django 5.1.4 on 2026-02-07 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_remove_home_banner_description_home_banner_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'end_date'], name='masters_cou_is_acti_c16876_idx'),
        ),
        migrations.AddIndex(
            model_name='home_banner',
            index=models.Index(fields=['is_active'], name='masters_hom_is_acti_66d366_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='masters_med_is_acti_c827e9_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['user', '-created_at'], name='masters_pre_user_id_62637c_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['is_active'], name='masters_tre_is_acti_4f5e98_idx'),
        ),
    ]
