# Generated by Django 5.1.4 on 2026-02-07 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_coupon_masters_cou_is_acti_c16876_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', '-created_at'], name='masters_enq_status_863e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['user', '-created_at'], name='masters_enq_user_id_fa5ff0_idx'),
        ),
    ]
