"""
Django settings for dentist project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hy*b1s0=k72d9oro7%#tutlb2!jl*2txbxm)^pt_98+*qwbn7h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'users',
    'masters',
    'doctor',
    'customer',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'dentist.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",
    "https://admin.toothtrack.in",  # production admin / same-host app
]
# Allow DELETE and other methods (fixes status 0 when app sends DELETE)
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# Allow Authorization header (required for JWT / Bearer)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-requested-with",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}


# OTP Configuration for msg.msgclub.net
MSG_CLUB_API_URL = "http://msg.msgclub.net/rest/services/sendSMS/sendGroupSms"
MSG_CLUB_API_KEY = "5f4e34db5673b2ee18ee66442e73d45"  # AUTH_KEY for msg.msgclub.net
MSG_CLUB_SENDER_ID = "TOOTHT"  # Sender ID for SMS
MSG_CLUB_ROUTE_ID = "8"  # Route ID (default: 1)
MSG_CLUB_SMS_CONTENT_TYPE = "english"  # SMS content type
OTP_MESSAGE_TEMPLATE = "OTP {otp_code} to verify your dental record on ToothTrack. Track treatment, reports & get 24x7 dental support. Download ToothTrack App. SNEHAL DIGITAL VENTURES PRIVATE LIMITED"  # OTP message template
OTP_EXPIRY_MINUTES = 5  # OTP expires after 5 minutes
OTP_LENGTH = 6  # 6-digit OTP

# Push notifications: Firebase Admin SDK (firebase_key.json). Legacy Server key only if you set it below.
FCM_SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, "dentist", "firebase_key.json")
FCM_SERVER_KEY = ""  # optional: set to legacy Server key if not using Firebase Admin

from datetime import timedelta


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
}


HTML2PDF_API_KEY = 'IjjR93npHaOZ6bXt6BmHdt2AwYRh3LBoe3hIYz0wBkHddGoa79PF00BB9cgPAdVl'
GOOGLE_MAPS_API_KEY = 'AIzaSyDSHEo7c3hgK2fl7LdLcmbB2dZa4Z0aOBY'



# Razorpay API keys
RAZORPAY_KEY_ID = "rzp_live_RxliNUJgfo2jZk"
RAZORPAY_KEY_SECRET = "GI66GvcBLwnKrTCbLtCgxrWN"       # Secret key (for backend API calls)
RAZORPAY_WEBHOOK_SECRET = "AIzaSyDSHEo7c3hgK2fl7LdLcmbB2dZa4Z0aOBY"   # Secret string to verify webhooks



ROOT_URLCONF = 'dentist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


WSGI_APPLICATION = 'dentist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Ensure a "logs" folder exists in your project root (for local dev)
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s: %(levelname)s: %(message)s"
        },
    },
    "handlers": {
        "request_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            # ✅ Use platform-safe path
            "filename": os.path.join(LOG_DIR, "requests.log"),
            "formatter": "verbose",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "webhook.log"),
            "formatter": "verbose",
        },
        # Optional console handler (so you also see logs in terminal)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "request_log": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "razorpay_webhook": {
            "handlers": ["webhook_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "otp_service": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "customer.notification_services": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "customer.push_services": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "customer.views": {
            "handlers": ["request_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}





# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AUTH_USER_MODEL = 'users.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
