# Generated by Django 5.1.4 on 2025-04-25 22:08

import django.db.models.deletion
import doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('masters', '0004_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dose_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('dose', models.CharField(choices=[('half', 'Half'), ('1', '1'), ('5 ml', '5 ml'), ('10 ml', '10 ml'), ('15 ml', '15 ml'), ('20 ml', '20 ml')], max_length=20)),
                ('meal_relation', models.CharField(choices=[('before_breakfast', 'Before Breakfast'), ('after_breakfast', 'After Breakfast'), ('before_lunch', 'Before Lunch'), ('after_lunch', 'After Lunch'), ('before_dinner', 'Before Dinner'), ('after_dinner', 'After Dinner')], max_length=30)),
                ('duration_in_days', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medicines', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('house_building', models.CharField(blank=True, max_length=120)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('about_doctor', models.CharField(max_length=500)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('remark', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.TimeField(default=doctor.models.current_time)),
                ('available_to', models.TimeField(default=doctor.models.current_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video_call_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
