# Generated by Django 5.1.4 on 2025-04-25 22:20

import django.db.models.deletion
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment_medicine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='appoinment_medicine',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medicines', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(default=doctor.models.current_time),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(default=doctor.models.current_time),
        ),
    ]
