# Generated by Django 5.1.4 on 2025-04-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic_address',
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='house_building',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='locality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
