# Generated by Django 5.1.4 on 2025-04-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
