# Generated by Django 5.1.4 on 2025-04-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_appointment_customer_alter_appointment_slot'),
        ('doctor', '0008_treatment_treatmentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='customer.appointment'),
            preserve_default=False,
        ),
    ]
