# Generated by Django 5.1.4 on 2025-04-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_treatment_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentstep',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='treatmentstep',
            name='step_number',
        ),
    ]
