# Generated by Django 5.1.4 on 2025-09-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_appointment_booking_for_appointment_doctor'),
        ('doctor', '0013_remove_doctor_experience_remove_doctor_mobile_no_and_more'),
        ('masters', '0012_home_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosdsctor_medicines', to='customer.appointment'),
        ),
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_wdefredsasmedicines', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swweeq', to='masters.medicine'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trewreeatment', to='customer.appointment'),
        ),
    ]
