# Generated by Django 5.1.4 on 2025-09-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_appoinment_medicine_appointment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment_medicine',
            name='customer',
        ),
        migrations.AddField(
            model_name='appoinment_medicine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_wdefredsasmedicines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
