# Generated by Django 5.1.4 on 2025-09-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_appoinment_medicine_customer_and_more'),
        ('masters', '0015_alter_treatmentstep_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_treatments', to='masters.treatment'),
            preserve_default=False,
        ),
    ]
