# Generated by Django 5.1.4 on 2025-09-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_treatment_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentstep',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatmentstep',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='TreatmentStep',
        ),
    ]
