# Generated by Django 5.1.4 on 2025-09-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_appointment_booking_for_appointment_doctor'),
        ('doctor', '0017_remove_treatmentstep_treatment_and_more'),
        ('masters', '0015_alter_treatmentstep_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='customer.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_treatments', to='doctor.doctor')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_treatments', to='masters.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTreatmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('appointment_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='doctor.appointmenttreatment')),
            ],
        ),
    ]
