# Generated by Django 5.1.4 on 2025-09-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_appointment_status'),
        ('doctor', '0020_lab_labwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labwork',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_works', to='customer.appointment'),
        ),
    ]
