# Generated by Django 5.1.4 on 2025-09-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_inventoryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
