# Generated by Django 5.1.4 on 2025-09-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_dob_remove_customer_gender_and_more'),
        ('doctor', '0025_appointmenttreatmentstep_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='customer.appointment')),
            ],
        ),
    ]
