# Generated by Django 5.1.4 on 2025-09-22 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_appointmentledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttreatmentstep',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
