# Generated by Django 5.1.4 on 2025-09-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_doctorleave_doctor'),
        ('masters', '0017_helpquestion_for_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='to_time',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='masters.slot'),
            preserve_default=False,
        ),
    ]
