# Generated by Django 5.1.4 on 2025-09-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
    ]
