# Generated by Django 5.1.4 on 2025-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_remove_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttreatmentstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
