# Generated by Django 5.1.4 on 2025-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_alter_appointmenttreatmentstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_consultation_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
