# Generated by Django 5.1.4 on 2025-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_doctor_clinic_consultation_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_image',
            field=models.ImageField(blank=True, null=True, upload_to='clinics'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_consultation_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
