# Generated by Django 5.1.4 on 2025-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_tooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_logo'),
        ),
    ]
