# Generated by Django 5.1.4 on 2025-09-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_doctor_clinic_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
