# Generated by Django 5.1.4 on 2025-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0039_remove_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='applicable_treatments',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_from',
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
