# Generated by Django 5.1.4 on 2025-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_remove_offer_applicable_treatments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdocument',
            name='title',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('document', 'Document'), ('report', 'Report')], default='document', max_length=50),
        ),
    ]
