# Generated by Django 5.1.4 on 2025-10-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_alter_lab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
