# Generated by Django 5.1.4 on 2025-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctor_latitude_doctor_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentledger',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
