# Generated by Django 5.1.4 on 2025-10-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_appointmentledger_date_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='designation',
        ),
    ]
