# Generated by Django 5.1.4 on 2025-10-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_remove_doctor_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='house_building',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
    ]
