# Generated by Django 5.1.4 on 2025-10-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0049_doctor_city_doctor_country_doctor_house_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='house_building',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='locality',
        ),
    ]
