# Generated by Django 5.1.4 on 2026-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_rename_house_building_doctor_street_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttreatmentstep',
            name='date',
            field=models.DateField(),
        ),
    ]
