# Generated by Django 5.1.4 on 2026-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_alter_appointmenttreatmentstep_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='dose_time',
            field=models.JSONField(default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']"),
        ),
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='meal_relation',
            field=models.CharField(choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal')], max_length=30),
        ),
    ]
