# Generated by Django 5.1.4 on 2026-01-10 12:03

from django.db import migrations, models
import json


def fix_dose_time_json(apps, schema_editor):
    """Fix existing dose_time values to be valid JSON using raw SQL to avoid validation errors"""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Get all records with their raw dose_time values using raw SQL
        # This bypasses Django ORM validation
        cursor.execute("SELECT id, dose_time FROM doctor_appoinment_medicine")
        
        valid_times = ['morning', 'afternoon', 'night']
        
        for row in cursor.fetchall():
            record_id, dose_time_value = row
            
            try:
                # If None, keep as None (nullable field)
                if dose_time_value is None:
                    continue
                
                # Try to parse as JSON first
                parsed_value = None
                if isinstance(dose_time_value, str):
                    try:
                        parsed_value = json.loads(dose_time_value)
                    except json.JSONDecodeError:
                        # Not valid JSON - might be old string value
                        parsed_value = dose_time_value
                else:
                    parsed_value = dose_time_value
                
                # Determine the fixed value
                fixed_value = None
                
                # If it's a list, validate contents
                if isinstance(parsed_value, list):
                    valid_list = [time for time in parsed_value if time in valid_times]
                    fixed_value = json.dumps(valid_list if valid_list else [])
                # If it's a string (from old CharField), convert to list
                elif isinstance(parsed_value, str) and parsed_value in valid_times:
                    fixed_value = json.dumps([parsed_value])
                else:
                    # Invalid value, set to empty list
                    fixed_value = json.dumps([])
                
                # Update using parameterized query (works with SQLite ? and PostgreSQL %s)
                cursor.execute(
                    "UPDATE doctor_appoinment_medicine SET dose_time = ? WHERE id = ?",
                    [fixed_value, record_id]
                )
                    
            except Exception as e:
                # If there's any error, set to empty list JSON
                try:
                    fixed_value = json.dumps([])
                    cursor.execute(
                        "UPDATE doctor_appoinment_medicine SET dose_time = ? WHERE id = ?",
                        [fixed_value, record_id]
                    )
                except:
                    pass  # Skip if we can't fix it


def reverse_fix_dose_time_json(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0052_alter_appoinment_medicine_dose_time_and_more'),
    ]

    operations = [
        # First, fix all existing records to have valid JSON
        migrations.RunPython(fix_dose_time_json, reverse_fix_dose_time_json),
        # Then alter the field to allow null
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
