# Generated by Django 5.1.4 on 2026-01-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0052_alter_appoinment_medicine_dose_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
