# Generated by Django 5.1.4 on 2026-01-10 12:03

from django.db import migrations, models
import json


def fix_dose_time_json(apps, schema_editor):
    """Fix existing dose_time values to be valid JSON"""
    AppoinmentMedicine = apps.get_model('doctor', 'Appoinment_Medicine')
    
    for medicine in AppoinmentMedicine.objects.all():
        try:
            # If dose_time is None, set to empty list
            if medicine.dose_time is None:
                medicine.dose_time = []
                medicine.save(update_fields=['dose_time'])
                continue
            
            # If it's already a list, validate it
            if isinstance(medicine.dose_time, list):
                # Ensure all values are valid
                valid_times = ['morning', 'afternoon', 'night']
                valid_list = [time for time in medicine.dose_time if time in valid_times]
                if valid_list != medicine.dose_time:
                    medicine.dose_time = valid_list if valid_list else []
                    medicine.save(update_fields=['dose_time'])
                continue
            
            # If it's a string (from old CharField), convert to list
            if isinstance(medicine.dose_time, str):
                valid_times = ['morning', 'afternoon', 'night']
                if medicine.dose_time in valid_times:
                    medicine.dose_time = [medicine.dose_time]
                else:
                    medicine.dose_time = []
                medicine.save(update_fields=['dose_time'])
                continue
            
            # For any other invalid type, set to empty list
            medicine.dose_time = []
            medicine.save(update_fields=['dose_time'])
            
        except (TypeError, ValueError, AttributeError, json.JSONDecodeError) as e:
            # If there's any error, set to empty list
            medicine.dose_time = []
            medicine.save(update_fields=['dose_time'])


def reverse_fix_dose_time_json(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0052_alter_appoinment_medicine_dose_time_and_more'),
    ]

    operations = [
        # First, fix all existing records to have valid JSON
        migrations.RunPython(fix_dose_time_json, reverse_fix_dose_time_json),
        # Then alter the field to allow null
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=list, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
