# Generated by Django 5.1.4 on 2026-01-10 12:07

from django.db import migrations
import json


def fix_existing_dose_time_data(apps, schema_editor):
    """Fix all existing Appoinment_Medicine records to have valid JSON in dose_time"""
    AppoinmentMedicine = apps.get_model('doctor', 'Appoinment_Medicine')
    
    for medicine in AppoinmentMedicine.objects.all():
        try:
            # Skip if already None (valid for nullable field)
            if medicine.dose_time is None:
                continue
            
            # If it's already a valid list, validate contents
            if isinstance(medicine.dose_time, list):
                valid_times = ['morning', 'afternoon', 'night']
                valid_list = [time for time in medicine.dose_time if time in valid_times]
                if valid_list != medicine.dose_time:
                    medicine.dose_time = valid_list if valid_list else []
                    medicine.save(update_fields=['dose_time'])
                continue
            
            # If it's a string (from old CharField migration), convert to list
            if isinstance(medicine.dose_time, str):
                valid_times = ['morning', 'afternoon', 'night']
                if medicine.dose_time in valid_times:
                    medicine.dose_time = [medicine.dose_time]
                else:
                    # Invalid string value, set to empty list
                    medicine.dose_time = []
                medicine.save(update_fields=['dose_time'])
                continue
            
            # For any other type (int, float, dict, etc.), set to empty list
            medicine.dose_time = []
            medicine.save(update_fields=['dose_time'])
            
        except Exception as e:
            # If there's any error accessing or saving, set to empty list
            print(f"Error fixing dose_time for Appoinment_Medicine {medicine.id}: {e}")
            try:
                medicine.dose_time = []
                medicine.save(update_fields=['dose_time'])
            except:
                pass  # If we can't save, skip this record


def reverse_fix_existing_dose_time_data(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0053_alter_appoinment_medicine_dose_time'),
    ]

    operations = [
        migrations.RunPython(fix_existing_dose_time_data, reverse_fix_existing_dose_time_data),
    ]
