# Generated by Django 5.1.4 on 2026-01-10 12:08

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0054_fix_appoinment_medicine_dose_time_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_medicine',
            name='dose_time',
            field=models.JSONField(blank=True, default=doctor.models.default_dose_time_list, help_text="List of selected times: ['morning', 'afternoon', 'night']", null=True),
        ),
    ]
