# Generated by Django 5.1.4 on 2026-01-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0055_alter_appoinment_medicine_dose_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='weekly_off_days',
            field=models.JSONField(blank=True, default=list, help_text="List of weekly off days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']"),
        ),
    ]
