# Generated by Django 5.1.4 on 2026-02-07 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_appointment_customer_ap_user_id_308186_idx_and_more'),
        ('doctor', '0056_doctor_weekly_off_days'),
        ('masters', '0034_coupon_masters_cou_is_acti_c16876_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appoinment_medicine',
            index=models.Index(fields=['appointment', '-created_at'], name='doctor_appo_appoint_98ee0a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentdocument',
            index=models.Index(fields=['appointment', '-uploaded_at'], name='doctor_appo_appoint_d71bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmenttreatment',
            index=models.Index(fields=['appointment', '-created_at'], name='doctor_appo_appoint_ade88f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='doctor_doct_is_acti_c8f073_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['doctor', 'day', 'is_active'], name='doctor_doct_doctor__53cc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='doctor_expe_user_id_fe92e1_idx'),
        ),
        migrations.AddIndex(
            model_name='labwork',
            index=models.Index(fields=['appointment', '-created_at'], name='doctor_labw_appoint_589f48_idx'),
        ),
        migrations.AddIndex(
            model_name='labwork',
            index=models.Index(fields=['lab', 'status'], name='doctor_labw_lab_id_a540cf_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['user', '-created_at'], name='doctor_offe_user_id_5ca820_idx'),
        ),
        migrations.AddIndex(
            model_name='video_call_history',
            index=models.Index(fields=['doctor', '-timestamp'], name='doctor_vide_doctor__83994b_idx'),
        ),
        migrations.AddIndex(
            model_name='video_call_history',
            index=models.Index(fields=['user', '-timestamp'], name='doctor_vide_user_id_65fa90_idx'),
        ),
    ]
